### ISSUE TITLE
Unable to download DataSet.zip from DropBox: download ends, throttled?

### ISSUE THREAD

**Issue by avantol** [mlachmish/MusicGenreClassification#1]
Is there another service for publishing/downloading this dataset that doesn't have a download size limit? (apparently it's 1.6 GB)

DropBox has a (stealthy) limit, it appears, after many attempts.

Thanks....

**Comment by mlachmish** [comment]
Hi @avantol, I've uploaded the file again and did checked that the complete file can be downloaded. Please try the new link and if you run into any issue please share with me.

https://www.dropbox.com/s/8ohx6m23co1qaz3/DataSet.zip?dl=0
