### ISSUE TITLE
Dataset 

### ISSUE THREAD

**Issue by Tortoise17** [mlachmish/MusicGenreClassification#10]
Dear Friend. 
I have to request to please upload the dataset again .. I cannot download from the available link. I would like to test .. !! Thank you for kind help and support. Greetings.

**Comment by varunreddy24** [comment]
I am unable to find the dataset, the link shows that the traffic has been exceeded

**Comment by Tortoise17** [comment]
> I am unable to find the dataset, the link shows that the traffic has been exceeded

Follow the link and enjoy the data

wget http://opihi.cs.uvic.ca/sound/genres.tar.gz
